name: New Tweet
description: File a tweet
title: "[Tweet]: "
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What do you want to tweet?
      placeholder: Hello World!
    validations:
      required: true
