name: Issue Forms Body Parser

on: issues

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Grab body of latest issue
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Run Issue form parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
    - run: echo "${{ JSON.stringify(steps.parse.outputs.data) }}"
