name: Issue Forms Body Parser

on: issues

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Grab body of latest issue
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Run Issue form parser
      id: parse
      uses: peter-murray/issue-forms-body-parser@v2.0.0
      with:
        issue_id: ${{ github.event.issue.number }}
        separator: '###'
        label_marker_start: '>>'
        label_marker_end: '<<'
    - name: Show parsed data JSON
      run: |
        echo "${{ steps.parse.outputs.payload }}" >> ./tweets/"${{ github.event.issue.number }}".tweet
        cat ./tweets/"${{ github.event.issue.number }}".tweet
