name: Issue Forms Body Parser

on: issues

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Grab body of latest issue
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Run Issue form parser
      uses: stefanbuck/github-issue-parser@v2
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/new-tweet-request.yaml
    - run: |
        echo '${{ steps.issue-parser.outputs.jsonString }}' > bug-details.json
        jq '.tweet' bug-details.json
