name: Issue Forms Body Parser

on:
  issues:
    types: ['opened']
  issue_comment:
    types: ['created']
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Grab body of latest issue
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Run Issue form parser
      uses: stefanbuck/github-issue-parser@v2
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/new-tweet-request.yaml
    - run: |
        echo '${{ steps.issue-parser.outputs.jsonString }}' > bug-details.json
        string=$(jq '.tweet' bug-details.json)
        echo ${string:1:-1} >> tweets/${{ github.event.issue.number }}.tweet
        cat tweets/${{ github.event.issue.number }}.tweet
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        add-paths: |
          tweets/${{ github.event.issue.number }}.tweet
        commit-message: Add new tweet file via automation
        title: 'add: new tweet file via automation'
        body: |
          This PR is auto-generated.
          Fixes: #${{ github.event.issue.number }}
        branch: add/${{ github.event.issue.number }}
        base: main
        signoff: true
        delete-branch: true
        
